nameOverride: ""
fullnameOverride: ""

labels: { }
annotations: { }
deploymentLabels: { }
deploymentAnnotations: { }
podLabels: { }
podAnnotations: { }

containerName: "app"

image:
  registry: "docker.io"
  repository: "abrarov/docker-compose-init-container-app"
  tag: "latest"
  pullPolicy: "IfNotPresent"

livenessProbe:
  initialDelay: 5

readinessProbe:
  initialDelay: 5

replicaCount: 1

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  labels: { }
  annotations: { }
  port: 8080

ingress:
  labels: { }
  annotations: { }
  host: ""
  path: "/"
  tls:
    caCertificate: ""
    certificate: ""
    key: ""

app:
  trustStorePassword: "password_of_6_chars_min"
  port: 8080
  configDir: "/config"
  defaultJvmOptions:
    - "-XX:+PerfDisableSharedMem"
  extraJvmOptions: [ ]

init:
  containerName: "init"
  image:
    registry: "docker.io"
    repository: "abrarov/docker-compose-init-container-initializer"
    tag: "latest"
    pullPolicy: "IfNotPresent"

test:
  podLabels: { }
  podAnnotations: { }
  containerName: "test"
  image:
    registry: "docker.io"
    repository: "curlimages/curl"
    tag: "latest"
    pullPolicy: "IfNotPresent"
