nameOverride: ""
fullnameOverride: ""

containerName: "app"

image:
  registry: "docker.io"
  name: "abrarov/docker-compose-init-container-app"
  tag: "latest"
  pull:
    policy: "IfNotPresent"

liveness:
  initialDelay: 5

readiness:
  initialDelay: 5

replicas: 1

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  port: 8080

ingress:
  host: ""
  path: "/"
  tls:
    caCertificate: ""
    certificate: ""
    key: ""

app:
  trustStorePassword: "password_of_6_chars_min"
  port: 8080
  configDir: "/config"
  defaultJvmOptions:
    - "-XX:+PerfDisableSharedMem"
  extraJvmOptions: []

init:
  containerName: "init"
  image:
    registry: "docker.io"
    name: "abrarov/docker-compose-init-container-initializer"
    tag: "latest"
    pull:
      policy: "IfNotPresent"

test:
  containerName: "test"
  image:
    registry: "docker.io"
    name: "curlimages/curl"
    tag: "latest"
    pull:
      policy: "IfNotPresent"
