nameOverride: ""
fullnameOverride: ""

container:
  main:
    name: "app"
    image:
      repository:
      registry:
      name: "app"
      tag: "latest"
  init:
    name: "init"
    image:
      repository:
      registry:
      name: "app-initializer"
      tag: "latest"
  test:
    name: "test"
    image:
      repository: "curlimages/curl"
      tag: "latest"

replicas: 1
imagePullPolicy: "IfNotPresent"
imagePullSecrets: []

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true

service:
  type: "ClusterIP"
  port: 8443

route:
  host:
  path: "/"
  tls:
    caCertificate:
    certificate:
    key:

app:
  tls:
    keyStorePassword: "pass"
    keyAlias: "alias"
  trustStorePassword: "password_of_6_chars_min"
  port: 8443
  configDir: "/config"
  defaultJvmOptions:
    - "-XX:+PerfDisableSharedMem"
  extraJvmOptions: []
