version: '2.1'

services:
  helper:
    image: 'abrarov/docker-compose-init-container-helper'
    volumes:
      - '/helper'
  init:
    image: 'abrarov/docker-compose-init-container-initializer'
    command: ['/helper/busybox', 'sh', '/helper/init.sh']
    volumes_from:
      - 'helper:ro'
    volumes:
      - '/config'
  app:
    image: 'abrarov/docker-compose-init-container-app'
    user: '100502'
    command: ['/helper/dockerize', '-wait', 'tcp://init:8080', '-timeout', '60s',
              '/tini', '-s', '-e', '130', '-e', '143', '--', '/usr/bin/java', '-jar', '/app.jar']
    volumes_from:
      - 'helper:ro'
      - 'init:ro'