version: '2.1'

services:
  init:
    image: 'abrarov/docker-compose-init-container-initializer'
    command:
      - '/bin/sh'
      - '-c'
      - 'touch /config/done'
    volumes:
      - '/config'

  helper:
    image: 'abrarov/docker-compose-init-container-helper'
    volumes:
      - '/helper'

  app:
    image: 'abrarov/docker-compose-init-container-app'
    user: '100502'
    command:
      - '/helper/dockerize'
      - '-wait'
      - 'file:////config/done'
      - '-timeout'
      - '60s'
      - '/tini'
      - '-s'
      - '-e'
      - '130'
      - '-e'
      - '143'
      - '--'
      - '/usr/bin/java'
      - '-jar'
      - '/app.jar'
    volumes_from:
      - 'helper:ro'
      - 'init:ro'