version: '2.1'

volumes:
  config:

services:
  app:
    image: 'abrarov/docker-compose-init-container-app'
    healthcheck:
      test:
        - 'CMD'
        - 'dockerize'
        - '-timeout'
        - '5s'
        - '-skip-tls-verify'
        - '-wait'
        - 'https://localhost:8443'
      interval: '10s'
      timeout: '1s'
      retries: 3
    environment:
      TINI_SUBREAPER: '1'
      JAVA_TOOL_OPTIONS: '-XX:+PerfDisableSharedMem ${JAVA_OPTIONS:-}'
      CA_BUNDLE_FILE: '/ca-cert.crt'
      TRUST_STORE_PASSWORD: 'password_of_6_chars_min'
      SERVER_PORT: '8443'
      TLS_KEY_FILE: '/tls-key.pem'
      TLS_CERT_FILE: '/tls-cert.crt'
      TLS_CA_CERT_FILE: '/ca-cert.crt'
      TLS_KEY_STORE_PASSWORD: 'pass'
      TLS_KEY_ALIAS: 'alias'
    read_only: true
    volumes:
      - '/tmp'
      - '../certificates/ca-cert.crt:/ca-cert.crt:ro'
      - '../certificates/tls-cert.crt:/tls-cert.crt:ro'
      - '../certificates/tls-key.pem:/tls-key.pem:ro'
    ports:
      - '443:8443'
    networks:
      default:
        aliases:
          - 'app.docker-compose-init-container.local'