apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "app.secretName" . | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  tlsKeyStorePassword: {{ .Values.app.tls.keyStorePassword | quote }}
  trustStorePassword: {{ .Values.app.trustStorePassword | quote }}
