apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.serviceName" . | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ include "app.serviceTlsSecretName" . | quote }}
spec:
  type: {{ .Values.service.type | quote }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "app.containerPortName" . | quote }}
      name: {{ include "app.servicePortName" . | quote }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
