apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "app.serviceName" . | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- include "app.componentLabels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- include "app.tplValuesRender" ( dict "value" .Values.labels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.service.labels }}
    {{- include "app.tplValuesRender" ( dict "value" .Values.service.labels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ include "app.serviceTlsSecretName" . | quote }}
    {{- if .Values.annotations }}
    {{- include "app.tplValuesRender" ( dict "value" .Values.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.service.annotations }}
    {{- include "app.tplValuesRender" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: "ClusterIP"
  ports:
    - name: {{ include "app.servicePortName" . | quote }}
      port: {{ .Values.service.port }}
      targetPort: {{ include "app.containerPortName" . | quote }}
  selector:
    {{- include "app.matchLabels" . | nindent 4 }}
    {{- include "app.componentLabels" . | nindent 4 }}
