FROM scratch

ADD ["rootfs.tar", "/"]

# Call some statically linked application which exits with zero exit code
CMD ["/helper/dockerize", "--version"]

LABEL name="@docker.repository@" \
    version="@project.version@" \
    release="@project.version@" \
    build-date="@git.commit.time@" \
    vcs-url="@git.remote.origin.url@" \
    vcs-type="git" \
    vcs-ref="@git.commit.id@"
