apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "app.secretName" . | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  trustStorePassword: {{ .Values.app.trustStorePassword | quote }}
