apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "app.secretName" . | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- include "app.componentLabels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- include "app.tplValuesRender" ( dict "value" .Values.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- include "app.tplValuesRender" ( dict "value" .Values.annotations "context" $ ) | nindent 4 }}
  {{- end }}
type: "Opaque"
stringData:
  trustStorePassword: {{ .Values.app.trustStorePassword | quote }}
