apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "app.deploymentName" . | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.container.main.name | quote }}
          image: {{ (printf "%s:%s" .Values.container.main.image.repository (.Values.container.main.image.tag | default .Chart.AppVersion)) | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          env:
            - name: "JAVA_TOOL_OPTIONS"
              value: {{ include "app.finalJvmOptions" . | quote }}
            - name: "TRUST_STORE_FILE"
              value: "{{ .Values.app.configDir }}/truststore.jks"
            - name: "TRUST_STORE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.secretName" . | quote }}
                  key: "trustStorePassword"
            - name: "SERVER_PORT"
              value: {{ .Values.app.port | quote }}
          ports:
            - name: {{ include "app.containerPortName" . | quote }}
              containerPort: {{ .Values.app.port }}
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: {{ include "app.containerPortName" . | quote }}
              scheme: {{ include "app.portScheme" . | upper | quote }}
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: {{ include "app.containerPortName" . | quote }}
              scheme: {{ include "app.portScheme" . | upper | quote }}
            initialDelaySeconds: 5
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - mountPath: "{{ .Values.app.configDir }}"
              name: "config-volume"
              readOnly: true
            - mountPath: "/tmp"
              name: "app-tmp-volume"
      initContainers:
        - name: {{ .Values.container.init.name | quote }}
          image: {{ (printf "%s:%s" .Values.container.init.image.repository (.Values.container.init.image.tag | default .Chart.AppVersion)) | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          env:
            - name: "TRUST_STORE_FILE"
              value: "{{ .Values.app.configDir }}/truststore.jks"
            - name: "TRUST_STORE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.secretName" . | quote }}
                  key: "trustStorePassword"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.app.configDir | quote }}
              name: "config-volume"
            - mountPath: "/tmp"
              name: "init-tmp-volume"
      volumes:
        - name: "config-volume"
          emptyDir: {}
        - name: "app-tmp-volume"
          emptyDir: {}
        - name: "init-tmp-volume"
          emptyDir: {}
