apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "app.tlsSecretName" . | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- include "app.componentLabels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- include "app.tplValuesRender" (dict "value" .Values.labels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- include "app.tplValuesRender" (dict "value" .Values.annotations "context" $) | nindent 4 }}
  {{- end }}
type: "kubernetes.io/tls"
data:
  {{- if .Values.ingress.tls.caCertificate }}
  tls.crt: {{ (printf "%v\n%v" (.Values.ingress.tls.certificate | trim) (.Values.ingress.tls.caCertificate | trim)) | b64enc | quote }}
  {{- else }}
  tls.crt: {{ .Values.ingress.tls.certificate | trim | b64enc | quote }}
  {{- end }}
  tls.key: {{ .Values.ingress.tls.key | trim | b64enc | quote }}
