apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: {{ include "app.ingressName" . | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- include "app.componentLabels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- include "app.tplValuesRender" (dict "value" .Values.labels "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.labels }}
    {{- include "app.tplValuesRender" (dict "value" .Values.ingress.labels "context" $) | nindent 4 }}
    {{- end }}
  annotations:
    checksum/secret: {{ omit (include (print $.Template.BasePath "/ingress-tls-secret.yaml") . | fromYaml) "metadata" | toYaml | sha256sum | quote }}
    {{- if .Values.annotations }}
    {{- include "app.tplValuesRender" (dict "value" .Values.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- include "app.tplValuesRender" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ include "app.tlsSecretName" . | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: "Prefix"
            backend:
              service:
                name: {{ include "app.serviceName" . | quote }}
                port:
                  name: {{ include "app.servicePortName" . | quote }}
