apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.serviceName" . | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "app.containerPortName" . | quote }}
      name: {{ include "app.servicePortName" . | quote }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
